// swift-tools-version: 5.9
import PackageDescription

// NecropsyKit is Foundation-only and builds anywhere, which is what lets its
// decoding be tested in CI against fixtures generated by the Python API.
// NecropsyPanel is SwiftUI and is guarded with `#if canImport(SwiftUI)`, so it
// compiles to nothing off Apple platforms rather than breaking the build.
let package = Package(
    name: "Necropsy",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "NecropsyKit", targets: ["NecropsyKit"]),
        .library(name: "NecropsyPanel", targets: ["NecropsyPanel"]),
    ],
    targets: [
        .target(name: "NecropsyKit"),
        .target(
            name: "NecropsyPanel",
            dependencies: ["NecropsyKit"],
            exclude: ["README.md"]
        ),
        // Fixtures are read from `gui/Fixtures` by path, not bundled: they are a
        // repo artefact regenerated from the Python API, not shipped code.
        .testTarget(name: "NecropsyKitTests", dependencies: ["NecropsyKit"]),
    ]
)
