"""Initial Necropsy schema: cases, samples, artifacts, jobs, findings, next actions, audit.

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-04 20:57:09.184363
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=True),
    sa.Column('object_id', sa.String(length=120), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_object_id'), ['object_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANALYSING', 'CONTAINED', 'CLOSED', name='casestatus', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('host_engagement_ref', sa.String(length=200), nullable=True),
    sa.Column('ai_disclosure_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_host_engagement_ref'), ['host_engagement_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('tlsh', sa.String(length=72), nullable=True),
    sa.Column('ssdeep', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('magic', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Enum('PE', 'ELF', 'MACHO', 'OFFICE', 'SCRIPT', 'ARCHIVE', 'PDF', 'SHORTCUT', 'UNKNOWN', name='filetype', native_enum=False), nullable=False),
    sa.Column('arch', sa.Enum('X86', 'X86_64', 'ARM', 'ARM64', 'MIXED', 'NOT_APPLICABLE', 'UNKNOWN', name='arch', native_enum=False), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('storage_state', sa.Enum('VAULTED', 'QUARANTINED', 'PURGED', name='storagestate', native_enum=False), nullable=False),
    sa.Column('vault_uri', sa.String(length=500), nullable=True),
    sa.Column('identity_json', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_arch'), ['arch'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_md5'), ['md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_sha1'), ['sha1'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_sha256'), ['sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_samples_tlsh'), ['tlsh'], unique=False)

    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('IDENTIFY', 'HASH_PIVOT', 'STATIC_TRIAGE', 'YARA_SCAN', 'GHIDRA_DECOMPILE', 'DETONATE', 'AI_SUMMARISE', name='jobkind', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='jobstate', native_enum=False), nullable=False),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker', sa.String(length=120), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_state'), ['state'], unique=False)

    op.create_table('case_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('observed_filename', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('UPLOAD', 'PATH', 'URL', 'SANDBOX_DROP', name='samplesource', native_enum=False), nullable=False),
    sa.Column('submitted_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sample_id', name='uq_case_sample')
    )
    with op.batch_alter_table('case_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_samples_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_samples_sample_id'), ['sample_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('UNPACKED', 'PCAP', 'MEMDUMP', 'GHIDRA_PROJECT', 'SCREENSHOT', 'REPORT', 'OTHER', name='artifactkind', native_enum=False), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('vault_uri', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('producer', sa.Enum('INTAKE', 'PE', 'YARA', 'RIZIN', 'GHIDRA', 'SYSMON', 'ZEEK', 'AI', 'CORRELATION', name='producer', native_enum=False), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attack_json', sa.JSON(), nullable=False),
    sa.Column('kill_chain_phase', sa.Enum('RECONNAISSANCE', 'WEAPONISATION', 'DELIVERY', 'EXPLOITATION', 'INSTALLATION', 'COMMAND_AND_CONTROL', 'ACTIONS_ON_OBJECTIVES', name='killchainphase', native_enum=False), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('elastic_doc_id', sa.String(length=120), nullable=True),
    sa.Column('mirrored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'dedupe_key', name='uq_finding_dedupe')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_kill_chain_phase'), ['kill_chain_phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_producer'), ['producer'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_type'), ['type'], unique=False)

    op.create_table('next_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('origin_job_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('risk_json', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_s', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('unavailable_reason', sa.String(length=300), nullable=True),
    sa.Column('state', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'EXECUTED', 'EXPIRED', name='actionstate', native_enum=False), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('resulting_job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_next_actions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_next_actions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_next_actions_origin_job_id'), ['origin_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_next_actions_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_next_actions_state'))
        batch_op.drop_index(batch_op.f('ix_next_actions_origin_job_id'))
        batch_op.drop_index(batch_op.f('ix_next_actions_kind'))
        batch_op.drop_index(batch_op.f('ix_next_actions_case_id'))

    op.drop_table('next_actions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_type'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_sample_id'))
        batch_op.drop_index(batch_op.f('ix_findings_producer'))
        batch_op.drop_index(batch_op.f('ix_findings_kill_chain_phase'))
        batch_op.drop_index(batch_op.f('ix_findings_job_id'))
        batch_op.drop_index(batch_op.f('ix_findings_case_id'))

    op.drop_table('findings')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifacts_sample_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_job_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('case_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_samples_sample_id'))
        batch_op.drop_index(batch_op.f('ix_case_samples_case_id'))

    op.drop_table('case_samples')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_sample_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_case_id'))

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_tlsh'))
        batch_op.drop_index(batch_op.f('ix_samples_sha256'))
        batch_op.drop_index(batch_op.f('ix_samples_sha1'))
        batch_op.drop_index(batch_op.f('ix_samples_md5'))
        batch_op.drop_index(batch_op.f('ix_samples_file_type'))
        batch_op.drop_index(batch_op.f('ix_samples_arch'))

    op.drop_table('samples')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_host_engagement_ref'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_object_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
