"""Phase 2: decompiled function storage, so the GUI can page functions and Phase 5 can attach summaries.

Revision ID: 0002_functions
Revises: 0001_initial
Create Date: 2026-09-04 23:42:51.248511
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002_functions'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_thunk', sa.Boolean(), nullable=False),
    sa.Column('calling_convention', sa.String(length=60), nullable=True),
    sa.Column('parameter_count', sa.Integer(), nullable=False),
    sa.Column('calls_json', sa.JSON(), nullable=False),
    sa.Column('decompiled', sa.Text(), nullable=True),
    sa.Column('decompile_error', sa.Text(), nullable=True),
    sa.Column('code_sha256', sa.String(length=64), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summarised_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'address', name='uq_function_address')
    )
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_functions_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_functions_code_sha256'), ['code_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_functions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_functions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_functions_sample_id'), ['sample_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_functions_sample_id'))
        batch_op.drop_index(batch_op.f('ix_functions_name'))
        batch_op.drop_index(batch_op.f('ix_functions_job_id'))
        batch_op.drop_index(batch_op.f('ix_functions_code_sha256'))
        batch_op.drop_index(batch_op.f('ix_functions_address'))

    op.drop_table('functions')
    # ### end Alembic commands ###
