"""Phase 3: detonation records -- target fingerprint, telemetry counts and the readability verdict.

Revision ID: 0003_detonations
Revises: 0002_functions
Create Date: 2026-09-05 08:33:01.807081
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0003_detonations'
down_revision = '0002_functions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detonations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('target', sa.String(length=60), nullable=False),
    sa.Column('target_arch', sa.String(length=20), nullable=False),
    sa.Column('target_os', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.String(length=200), nullable=False),
    sa.Column('egress', sa.Boolean(), nullable=False),
    sa.Column('fidelity', sa.String(length=20), nullable=False),
    sa.Column('fingerprint_json', sa.JSON(), nullable=False),
    sa.Column('guest_path', sa.String(length=500), nullable=True),
    sa.Column('guest_hostname', sa.String(length=200), nullable=True),
    sa.Column('exec_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('run_seconds', sa.Integer(), nullable=False),
    sa.Column('telemetry_events', sa.Integer(), nullable=False),
    sa.Column('telemetry_source', sa.String(length=120), nullable=True),
    sa.Column('telemetry_note', sa.Text(), nullable=True),
    sa.Column('network_json', sa.JSON(), nullable=False),
    sa.Column('behaviour_json', sa.JSON(), nullable=False),
    sa.Column('readable', sa.Boolean(), nullable=False),
    sa.Column('verdict_note', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detonations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detonations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detonations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detonations_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detonations_state'), ['state'], unique=False)

    # ### end Alembic commands ###


    # Widened alongside the detonation work: NoTargetConfigured messages name the
    # setting to fix, and 300 chars truncated exactly that half away. SQLite does
    # not enforce VARCHAR length, but Postgres would.
    with op.batch_alter_table("next_actions") as batch:
        batch.alter_column(
            "unavailable_reason",
            existing_type=sa.String(length=300),
            type_=sa.String(length=600),
            existing_nullable=True,
        )


def downgrade() -> None:
    with op.batch_alter_table("next_actions") as batch:
        batch.alter_column(
            "unavailable_reason",
            existing_type=sa.String(length=600),
            type_=sa.String(length=300),
            existing_nullable=True,
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detonations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detonations_state'))
        batch_op.drop_index(batch_op.f('ix_detonations_sample_id'))
        batch_op.drop_index(batch_op.f('ix_detonations_job_id'))
        batch_op.drop_index(batch_op.f('ix_detonations_case_id'))

    op.drop_table('detonations')
    # ### end Alembic commands ###
